### ISSUE TITLE
Dude the front-end team is mad over there

### ISSUE THREAD

**Issue by ghost** [bry-an/simple-weather-backend#6]
We don't deliver all the data we promised. What should we do?
@bry-an

**Comment by ghost** [comment]
What should we do ... @bry-an

**Comment by bry-an** [comment]
We should add humidity to the return object on the getWeather endpoint!

This might upset them further, but we're also going to need to change the URL `:(`

**Comment by ghost** [comment]
Reasonable enough!!! Let's do it!!!

**Comment by ghost** [comment]
These guys can stop complaining
#7

**Comment by ghost** [comment]
now
